custom: [
  "EVM (BSC/Polygon/Arbitrum/ERC20): 0x3acf78e721aa065bd1509735a3ace630fcd0f452",
  "USDT TRC-20: TMG1BZJswd8UacHANKVi9Veq5FqSbaMjAQ",
  "TON: UQDjf84AZSwuCPC3UWFv28p-V44zI-1lfhqCMfaex2Q-jDsY"
]
